// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminPushEmpireRanksToRegionsArgs {}

impl From<AdminPushEmpireRanksToRegionsArgs> for super::Reducer {
    fn from(args: AdminPushEmpireRanksToRegionsArgs) -> Self {
        Self::AdminPushEmpireRanksToRegions
    }
}

impl __sdk::InModule for AdminPushEmpireRanksToRegionsArgs {
    type Module = super::RemoteModule;
}

pub struct AdminPushEmpireRanksToRegionsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_push_empire_ranks_to_regions`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_push_empire_ranks_to_regions {
    /// Request that the remote module invoke the reducer `admin_push_empire_ranks_to_regions` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_push_empire_ranks_to_regions`] callbacks.
    fn admin_push_empire_ranks_to_regions(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_push_empire_ranks_to_regions`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminPushEmpireRanksToRegionsCallbackId`] can be passed to [`Self::remove_on_admin_push_empire_ranks_to_regions`]
    /// to cancel the callback.
    fn on_admin_push_empire_ranks_to_regions(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminPushEmpireRanksToRegionsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_push_empire_ranks_to_regions`],
    /// causing it not to run in the future.
    fn remove_on_admin_push_empire_ranks_to_regions(
        &self,
        callback: AdminPushEmpireRanksToRegionsCallbackId,
    );
}

impl admin_push_empire_ranks_to_regions for super::RemoteReducers {
    fn admin_push_empire_ranks_to_regions(&self) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_push_empire_ranks_to_regions",
            AdminPushEmpireRanksToRegionsArgs {},
        )
    }
    fn on_admin_push_empire_ranks_to_regions(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminPushEmpireRanksToRegionsCallbackId {
        AdminPushEmpireRanksToRegionsCallbackId(self.imp.on_reducer(
            "admin_push_empire_ranks_to_regions",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminPushEmpireRanksToRegions {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_admin_push_empire_ranks_to_regions(
        &self,
        callback: AdminPushEmpireRanksToRegionsCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_push_empire_ranks_to_regions", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_push_empire_ranks_to_regions`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_push_empire_ranks_to_regions {
    /// Set the call-reducer flags for the reducer `admin_push_empire_ranks_to_regions` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_push_empire_ranks_to_regions(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_push_empire_ranks_to_regions for super::SetReducerFlags {
    fn admin_push_empire_ranks_to_regions(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_push_empire_ranks_to_regions", flags);
    }
}
