// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireTransferWatchtowerOwnershipArgs {
    pub watchtower_entity_id: u64,
    pub target_empire_entity_id: u64,
}

impl From<EmpireTransferWatchtowerOwnershipArgs> for super::Reducer {
    fn from(args: EmpireTransferWatchtowerOwnershipArgs) -> Self {
        Self::EmpireTransferWatchtowerOwnership {
            watchtower_entity_id: args.watchtower_entity_id,
            target_empire_entity_id: args.target_empire_entity_id,
        }
    }
}

impl __sdk::InModule for EmpireTransferWatchtowerOwnershipArgs {
    type Module = super::RemoteModule;
}

pub struct EmpireTransferWatchtowerOwnershipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_transfer_watchtower_ownership`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_transfer_watchtower_ownership {
    /// Request that the remote module invoke the reducer `empire_transfer_watchtower_ownership` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_empire_transfer_watchtower_ownership`] callbacks.
    fn empire_transfer_watchtower_ownership(
        &self,
        watchtower_entity_id: u64,
        target_empire_entity_id: u64,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `empire_transfer_watchtower_ownership`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EmpireTransferWatchtowerOwnershipCallbackId`] can be passed to [`Self::remove_on_empire_transfer_watchtower_ownership`]
    /// to cancel the callback.
    fn on_empire_transfer_watchtower_ownership(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> EmpireTransferWatchtowerOwnershipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_empire_transfer_watchtower_ownership`],
    /// causing it not to run in the future.
    fn remove_on_empire_transfer_watchtower_ownership(
        &self,
        callback: EmpireTransferWatchtowerOwnershipCallbackId,
    );
}

impl empire_transfer_watchtower_ownership for super::RemoteReducers {
    fn empire_transfer_watchtower_ownership(
        &self,
        watchtower_entity_id: u64,
        target_empire_entity_id: u64,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "empire_transfer_watchtower_ownership",
            EmpireTransferWatchtowerOwnershipArgs {
                watchtower_entity_id,
                target_empire_entity_id,
            },
        )
    }
    fn on_empire_transfer_watchtower_ownership(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &u64) + Send + 'static,
    ) -> EmpireTransferWatchtowerOwnershipCallbackId {
        EmpireTransferWatchtowerOwnershipCallbackId(self.imp.on_reducer(
            "empire_transfer_watchtower_ownership",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::EmpireTransferWatchtowerOwnership {
                                    watchtower_entity_id,
                                    target_empire_entity_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, watchtower_entity_id, target_empire_entity_id)
            }),
        ))
    }
    fn remove_on_empire_transfer_watchtower_ownership(
        &self,
        callback: EmpireTransferWatchtowerOwnershipCallbackId,
    ) {
        self.imp
            .remove_on_reducer("empire_transfer_watchtower_ownership", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `empire_transfer_watchtower_ownership`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_empire_transfer_watchtower_ownership {
    /// Set the call-reducer flags for the reducer `empire_transfer_watchtower_ownership` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn empire_transfer_watchtower_ownership(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_empire_transfer_watchtower_ownership for super::SetReducerFlags {
    fn empire_transfer_watchtower_ownership(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("empire_transfer_watchtower_ownership", flags);
    }
}
