// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::region_exploration_info_type::RegionExplorationInfo;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportRegionExplorationInfoArgs {
    pub records: Vec<RegionExplorationInfo>,
}

impl From<ImportRegionExplorationInfoArgs> for super::Reducer {
    fn from(args: ImportRegionExplorationInfoArgs) -> Self {
        Self::ImportRegionExplorationInfo {
            records: args.records,
        }
    }
}

impl __sdk::InModule for ImportRegionExplorationInfoArgs {
    type Module = super::RemoteModule;
}

pub struct ImportRegionExplorationInfoCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_region_exploration_info`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_region_exploration_info {
    /// Request that the remote module invoke the reducer `import_region_exploration_info` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_import_region_exploration_info`] callbacks.
    fn import_region_exploration_info(
        &self,
        records: Vec<RegionExplorationInfo>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `import_region_exploration_info`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImportRegionExplorationInfoCallbackId`] can be passed to [`Self::remove_on_import_region_exploration_info`]
    /// to cancel the callback.
    fn on_import_region_exploration_info(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<RegionExplorationInfo>) + Send + 'static,
    ) -> ImportRegionExplorationInfoCallbackId;
    /// Cancel a callback previously registered by [`Self::on_import_region_exploration_info`],
    /// causing it not to run in the future.
    fn remove_on_import_region_exploration_info(
        &self,
        callback: ImportRegionExplorationInfoCallbackId,
    );
}

impl import_region_exploration_info for super::RemoteReducers {
    fn import_region_exploration_info(
        &self,
        records: Vec<RegionExplorationInfo>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "import_region_exploration_info",
            ImportRegionExplorationInfoArgs { records },
        )
    }
    fn on_import_region_exploration_info(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<RegionExplorationInfo>)
            + Send
            + 'static,
    ) -> ImportRegionExplorationInfoCallbackId {
        ImportRegionExplorationInfoCallbackId(self.imp.on_reducer(
            "import_region_exploration_info",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ImportRegionExplorationInfo { records },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, records)
            }),
        ))
    }
    fn remove_on_import_region_exploration_info(
        &self,
        callback: ImportRegionExplorationInfoCallbackId,
    ) {
        self.imp
            .remove_on_reducer("import_region_exploration_info", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `import_region_exploration_info`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_import_region_exploration_info {
    /// Set the call-reducer flags for the reducer `import_region_exploration_info` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn import_region_exploration_info(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_import_region_exploration_info for super::SetReducerFlags {
    fn import_region_exploration_info(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("import_region_exploration_info", flags);
    }
}
