// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::equipment_preset_state_type::EquipmentPresetState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportEquipmentPresetStateArgs {
    pub records: Vec<EquipmentPresetState>,
}

impl From<ImportEquipmentPresetStateArgs> for super::Reducer {
    fn from(args: ImportEquipmentPresetStateArgs) -> Self {
        Self::ImportEquipmentPresetState {
            records: args.records,
        }
    }
}

impl __sdk::InModule for ImportEquipmentPresetStateArgs {
    type Module = super::RemoteModule;
}

pub struct ImportEquipmentPresetStateCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_equipment_preset_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_equipment_preset_state {
    /// Request that the remote module invoke the reducer `import_equipment_preset_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_import_equipment_preset_state`] callbacks.
    fn import_equipment_preset_state(
        &self,
        records: Vec<EquipmentPresetState>,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `import_equipment_preset_state`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImportEquipmentPresetStateCallbackId`] can be passed to [`Self::remove_on_import_equipment_preset_state`]
    /// to cancel the callback.
    fn on_import_equipment_preset_state(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<EquipmentPresetState>) + Send + 'static,
    ) -> ImportEquipmentPresetStateCallbackId;
    /// Cancel a callback previously registered by [`Self::on_import_equipment_preset_state`],
    /// causing it not to run in the future.
    fn remove_on_import_equipment_preset_state(
        &self,
        callback: ImportEquipmentPresetStateCallbackId,
    );
}

impl import_equipment_preset_state for super::RemoteReducers {
    fn import_equipment_preset_state(
        &self,
        records: Vec<EquipmentPresetState>,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "import_equipment_preset_state",
            ImportEquipmentPresetStateArgs { records },
        )
    }
    fn on_import_equipment_preset_state(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<EquipmentPresetState>)
            + Send
            + 'static,
    ) -> ImportEquipmentPresetStateCallbackId {
        ImportEquipmentPresetStateCallbackId(self.imp.on_reducer(
            "import_equipment_preset_state",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ImportEquipmentPresetState { records },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, records)
            }),
        ))
    }
    fn remove_on_import_equipment_preset_state(
        &self,
        callback: ImportEquipmentPresetStateCallbackId,
    ) {
        self.imp
            .remove_on_reducer("import_equipment_preset_state", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `import_equipment_preset_state`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_import_equipment_preset_state {
    /// Set the call-reducer flags for the reducer `import_equipment_preset_state` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn import_equipment_preset_state(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_import_equipment_preset_state for super::SetReducerFlags {
    fn import_equipment_preset_state(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("import_equipment_preset_state", flags);
    }
}
